# Generated by Django 6.0.6 on 2026-07-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название курса")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите картинку",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Картинка",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание урока")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название урока")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание урока")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите картинку",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Картинка",
                    ),
                ),
                ("video_url", models.URLField(max_length=500, verbose_name="Ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Выберите курс, к которому относится урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
